curiosity:
  build: .
  command: node_modules/.bin/nodemon server.js
  environment:
    NODE_ENV: development
  ports:
    - '3000:3000'
  volumes:
    - .:/home/app/curiosity
    - /home/app/curiosity/node_modules
